### ISSUE TITLE
fatal error missing closing bracket

### ISSUE THREAD

**Issue by jgmac1106** [davidmead/Known-Listen#5]
I thought it was in my conflict merge but I downloaded your fork and I am still getting this error: syntax error, unexpected '}', expecting end of file

**Comment by davidmead** [comment]
Hmm. I'm running these [live on my site](https://davidjohnmead.com/content/listen/) at the moment without an issue @jgmac1106.

I can take a look when I get home, just in case I've not pushed something here that I fixed locally.

**Comment by jgmac1106** [comment]
I customized my footer and it ain't 100% legit so maybe that triggers as well. Will experiment when I get home

**Comment by davidmead** [comment]
Looking at GtHub Desktop I have no local changes.  So I assume that means everything I have on my machine is what you pulled

**Comment by davidmead** [comment]
I tried to grab just the files you mentioned in https://github.com/davidmead/Known-Listen/issues/3 @jgmac1106, but it looks like I grabbed everything, so now I have the same issue.

**Comment by davidmead** [comment]
OK. Big chunks of `Listen.tpl.php` were missing from your commit. I added them back in and my site is now working again. I pushed these changes back into my Master.

**Comment by jgmac1106** [comment]
Awesome. I always do more damage resolving code conflicts than anything I
fix.

**Comment by davidmead** [comment]
That's my job ;-)

Take a look and see if I've broken anything your end.

**Comment by davidmead** [comment]
OK. All my `listenAuthor` entries seem to have been blown away. Luckily I only had 11 entered. Updated the variable so it was the same that @cleverdevil changed it to in his commit, and (after entering them again) they display and pull back into the field when editing the post.
